export interface RoCity {
  name: string;
  county: string;
}

// municipii + orașe din România, pe județe — pentru autocomplete la adrese de cursă;
// nu e exhaustivă (comunele lipsesc), dar acoperă marea majoritate a traficului real de marfă
export const RO_CITIES: RoCity[] = [
  { name: 'București', county: 'București' },

  { name: 'Alba Iulia', county: 'Alba' },
  { name: 'Aiud', county: 'Alba' },
  { name: 'Blaj', county: 'Alba' },
  { name: 'Cugir', county: 'Alba' },
  { name: 'Ocna Mureș', county: 'Alba' },
  { name: 'Sebeș', county: 'Alba' },
  { name: 'Zlatna', county: 'Alba' },
  { name: 'Câmpeni', county: 'Alba' },
  { name: 'Abrud', county: 'Alba' },
  { name: 'Teiuș', county: 'Alba' },

  { name: 'Arad', county: 'Arad' },
  { name: 'Chișineu-Criș', county: 'Arad' },
  { name: 'Curtici', county: 'Arad' },
  { name: 'Ineu', county: 'Arad' },
  { name: 'Lipova', county: 'Arad' },
  { name: 'Nădlac', county: 'Arad' },
  { name: 'Pâncota', county: 'Arad' },
  { name: 'Pecica', county: 'Arad' },
  { name: 'Sântana', county: 'Arad' },
  { name: 'Sebiș', county: 'Arad' },

  { name: 'Pitești', county: 'Argeș' },
  { name: 'Câmpulung', county: 'Argeș' },
  { name: 'Curtea de Argeș', county: 'Argeș' },
  { name: 'Costești', county: 'Argeș' },
  { name: 'Mioveni', county: 'Argeș' },
  { name: 'Ștefănești', county: 'Argeș' },
  { name: 'Topoloveni', county: 'Argeș' },

  { name: 'Bacău', county: 'Bacău' },
  { name: 'Buhuși', county: 'Bacău' },
  { name: 'Comănești', county: 'Bacău' },
  { name: 'Dărmănești', county: 'Bacău' },
  { name: 'Moinești', county: 'Bacău' },
  { name: 'Onești', county: 'Bacău' },
  { name: 'Slănic-Moldova', county: 'Bacău' },
  { name: 'Târgu Ocna', county: 'Bacău' },

  { name: 'Oradea', county: 'Bihor' },
  { name: 'Aleșd', county: 'Bihor' },
  { name: 'Beiuș', county: 'Bihor' },
  { name: 'Marghita', county: 'Bihor' },
  { name: 'Salonta', county: 'Bihor' },
  { name: 'Săcueni', county: 'Bihor' },
  { name: 'Ștei', county: 'Bihor' },
  { name: 'Valea lui Mihai', county: 'Bihor' },
  { name: 'Vașcău', county: 'Bihor' },

  { name: 'Bistrița', county: 'Bistrița-Năsăud' },
  { name: 'Beclean', county: 'Bistrița-Năsăud' },
  { name: 'Năsăud', county: 'Bistrița-Năsăud' },
  { name: 'Sângeorz-Băi', county: 'Bistrița-Năsăud' },

  { name: 'Botoșani', county: 'Botoșani' },
  { name: 'Bucecea', county: 'Botoșani' },
  { name: 'Darabani', county: 'Botoșani' },
  { name: 'Dorohoi', county: 'Botoșani' },
  { name: 'Flămânzi', county: 'Botoșani' },
  { name: 'Săveni', county: 'Botoșani' },
  { name: 'Ștefănești', county: 'Botoșani' },

  { name: 'Brașov', county: 'Brașov' },
  { name: 'Codlea', county: 'Brașov' },
  { name: 'Făgăraș', county: 'Brașov' },
  { name: 'Ghimbav', county: 'Brașov' },
  { name: 'Predeal', county: 'Brașov' },
  { name: 'Rupea', county: 'Brașov' },
  { name: 'Săcele', county: 'Brașov' },
  { name: 'Victoria', county: 'Brașov' },
  { name: 'Zărnești', county: 'Brașov' },
  { name: 'Râșnov', county: 'Brașov' },

  { name: 'Brăila', county: 'Brăila' },
  { name: 'Făurei', county: 'Brăila' },
  { name: 'Ianca', county: 'Brăila' },
  { name: 'Însurăței', county: 'Brăila' },

  { name: 'Buzău', county: 'Buzău' },
  { name: 'Nehoiu', county: 'Buzău' },
  { name: 'Pătârlagele', county: 'Buzău' },
  { name: 'Pogoanele', county: 'Buzău' },
  { name: 'Râmnicu Sărat', county: 'Buzău' },

  { name: 'Reșița', county: 'Caraș-Severin' },
  { name: 'Anina', county: 'Caraș-Severin' },
  { name: 'Bocșa', county: 'Caraș-Severin' },
  { name: 'Băile Herculane', county: 'Caraș-Severin' },
  { name: 'Caransebeș', county: 'Caraș-Severin' },
  { name: 'Moldova Nouă', county: 'Caraș-Severin' },
  { name: 'Oravița', county: 'Caraș-Severin' },
  { name: 'Oțelu Roșu', county: 'Caraș-Severin' },

  { name: 'Călărași', county: 'Călărași' },
  { name: 'Budești', county: 'Călărași' },
  { name: 'Fundulea', county: 'Călărași' },
  { name: 'Lehliu Gară', county: 'Călărași' },
  { name: 'Oltenița', county: 'Călărași' },

  { name: 'Cluj-Napoca', county: 'Cluj' },
  { name: 'Câmpia Turzii', county: 'Cluj' },
  { name: 'Dej', county: 'Cluj' },
  { name: 'Gherla', county: 'Cluj' },
  { name: 'Huedin', county: 'Cluj' },
  { name: 'Turda', county: 'Cluj' },

  { name: 'Constanța', county: 'Constanța' },
  { name: 'Băneasa', county: 'Constanța' },
  { name: 'Cernavodă', county: 'Constanța' },
  { name: 'Eforie', county: 'Constanța' },
  { name: 'Hârșova', county: 'Constanța' },
  { name: 'Mangalia', county: 'Constanța' },
  { name: 'Medgidia', county: 'Constanța' },
  { name: 'Murfatlar', county: 'Constanța' },
  { name: 'Năvodari', county: 'Constanța' },
  { name: 'Negru Vodă', county: 'Constanța' },
  { name: 'Ovidiu', county: 'Constanța' },
  { name: 'Techirghiol', county: 'Constanța' },

  { name: 'Sfântu Gheorghe', county: 'Covasna' },
  { name: 'Baraolt', county: 'Covasna' },
  { name: 'Covasna', county: 'Covasna' },
  { name: 'Întorsura Buzăului', county: 'Covasna' },
  { name: 'Târgu Secuiesc', county: 'Covasna' },

  { name: 'Târgoviște', county: 'Dâmbovița' },
  { name: 'Fieni', county: 'Dâmbovița' },
  { name: 'Găești', county: 'Dâmbovița' },
  { name: 'Moreni', county: 'Dâmbovița' },
  { name: 'Pucioasa', county: 'Dâmbovița' },
  { name: 'Răcari', county: 'Dâmbovița' },
  { name: 'Titu', county: 'Dâmbovița' },

  { name: 'Craiova', county: 'Dolj' },
  { name: 'Băilești', county: 'Dolj' },
  { name: 'Bechet', county: 'Dolj' },
  { name: 'Calafat', county: 'Dolj' },
  { name: 'Dăbuleni', county: 'Dolj' },
  { name: 'Filiași', county: 'Dolj' },
  { name: 'Segarcea', county: 'Dolj' },

  { name: 'Galați', county: 'Galați' },
  { name: 'Berești', county: 'Galați' },
  { name: 'Tecuci', county: 'Galați' },

  { name: 'Giurgiu', county: 'Giurgiu' },
  { name: 'Bolintin-Vale', county: 'Giurgiu' },
  { name: 'Mihăilești', county: 'Giurgiu' },

  { name: 'Târgu Jiu', county: 'Gorj' },
  { name: 'Bumbești-Jiu', county: 'Gorj' },
  { name: 'Motru', county: 'Gorj' },
  { name: 'Novaci', county: 'Gorj' },
  { name: 'Rovinari', county: 'Gorj' },
  { name: 'Târgu Cărbunești', county: 'Gorj' },
  { name: 'Tismana', county: 'Gorj' },
  { name: 'Turceni', county: 'Gorj' },

  { name: 'Miercurea Ciuc', county: 'Harghita' },
  { name: 'Bălan', county: 'Harghita' },
  { name: 'Borsec', county: 'Harghita' },
  { name: 'Cristuru Secuiesc', county: 'Harghita' },
  { name: 'Gheorgheni', county: 'Harghita' },
  { name: 'Odorheiu Secuiesc', county: 'Harghita' },
  { name: 'Toplița', county: 'Harghita' },
  { name: 'Vlăhița', county: 'Harghita' },

  { name: 'Deva', county: 'Hunedoara' },
  { name: 'Aninoasa', county: 'Hunedoara' },
  { name: 'Brad', county: 'Hunedoara' },
  { name: 'Călan', county: 'Hunedoara' },
  { name: 'Geoagiu', county: 'Hunedoara' },
  { name: 'Hațeg', county: 'Hunedoara' },
  { name: 'Hunedoara', county: 'Hunedoara' },
  { name: 'Lupeni', county: 'Hunedoara' },
  { name: 'Orăștie', county: 'Hunedoara' },
  { name: 'Petrila', county: 'Hunedoara' },
  { name: 'Petroșani', county: 'Hunedoara' },
  { name: 'Simeria', county: 'Hunedoara' },
  { name: 'Uricani', county: 'Hunedoara' },
  { name: 'Vulcan', county: 'Hunedoara' },

  { name: 'Slobozia', county: 'Ialomița' },
  { name: 'Amara', county: 'Ialomița' },
  { name: 'Căzănești', county: 'Ialomița' },
  { name: 'Fetești', county: 'Ialomița' },
  { name: 'Fierbinți-Târg', county: 'Ialomița' },
  { name: 'Țăndărei', county: 'Ialomița' },
  { name: 'Urziceni', county: 'Ialomița' },

  { name: 'Iași', county: 'Iași' },
  { name: 'Hârlău', county: 'Iași' },
  { name: 'Pașcani', county: 'Iași' },
  { name: 'Târgu Frumos', county: 'Iași' },

  { name: 'Bragadiru', county: 'Ilfov' },
  { name: 'Buftea', county: 'Ilfov' },
  { name: 'Chitila', county: 'Ilfov' },
  { name: 'Măgurele', county: 'Ilfov' },
  { name: 'Otopeni', county: 'Ilfov' },
  { name: 'Pantelimon', county: 'Ilfov' },
  { name: 'Popești-Leordeni', county: 'Ilfov' },
  { name: 'Voluntari', county: 'Ilfov' },

  { name: 'Baia Mare', county: 'Maramureș' },
  { name: 'Baia Sprie', county: 'Maramureș' },
  { name: 'Borșa', county: 'Maramureș' },
  { name: 'Cavnic', county: 'Maramureș' },
  { name: 'Seini', county: 'Maramureș' },
  { name: 'Sighetu Marmației', county: 'Maramureș' },
  { name: 'Șomcuta Mare', county: 'Maramureș' },
  { name: 'Târgu Lăpuș', county: 'Maramureș' },
  { name: 'Tăuții-Măgherăuș', county: 'Maramureș' },
  { name: 'Ulmeni', county: 'Maramureș' },
  { name: 'Vișeu de Sus', county: 'Maramureș' },

  { name: 'Drobeta-Turnu Severin', county: 'Mehedinți' },
  { name: 'Baia de Aramă', county: 'Mehedinți' },
  { name: 'Orșova', county: 'Mehedinți' },
  { name: 'Strehaia', county: 'Mehedinți' },
  { name: 'Vânju Mare', county: 'Mehedinți' },

  { name: 'Târgu Mureș', county: 'Mureș' },
  { name: 'Iernut', county: 'Mureș' },
  { name: 'Luduș', county: 'Mureș' },
  { name: 'Miercurea Nirajului', county: 'Mureș' },
  { name: 'Reghin', county: 'Mureș' },
  { name: 'Sângeorgiu de Pădure', county: 'Mureș' },
  { name: 'Sărmașu', county: 'Mureș' },
  { name: 'Sighișoara', county: 'Mureș' },
  { name: 'Sovata', county: 'Mureș' },
  { name: 'Târnăveni', county: 'Mureș' },
  { name: 'Ungheni', county: 'Mureș' },

  { name: 'Piatra Neamț', county: 'Neamț' },
  { name: 'Bicaz', county: 'Neamț' },
  { name: 'Roman', county: 'Neamț' },
  { name: 'Roznov', county: 'Neamț' },
  { name: 'Târgu Neamț', county: 'Neamț' },

  { name: 'Slatina', county: 'Olt' },
  { name: 'Balș', county: 'Olt' },
  { name: 'Caracal', county: 'Olt' },
  { name: 'Corabia', county: 'Olt' },
  { name: 'Drăgănești-Olt', county: 'Olt' },
  { name: 'Piatra-Olt', county: 'Olt' },
  { name: 'Potcoava', county: 'Olt' },
  { name: 'Scornicești', county: 'Olt' },

  { name: 'Ploiești', county: 'Prahova' },
  { name: 'Azuga', county: 'Prahova' },
  { name: 'Băicoi', county: 'Prahova' },
  { name: 'Boldești-Scăeni', county: 'Prahova' },
  { name: 'Breaza', county: 'Prahova' },
  { name: 'Bușteni', county: 'Prahova' },
  { name: 'Câmpina', county: 'Prahova' },
  { name: 'Comarnic', county: 'Prahova' },
  { name: 'Mizil', county: 'Prahova' },
  { name: 'Plopeni', county: 'Prahova' },
  { name: 'Sinaia', county: 'Prahova' },
  { name: 'Slănic', county: 'Prahova' },
  { name: 'Urlați', county: 'Prahova' },
  { name: 'Vălenii de Munte', county: 'Prahova' },

  { name: 'Satu Mare', county: 'Satu Mare' },
  { name: 'Ardud', county: 'Satu Mare' },
  { name: 'Carei', county: 'Satu Mare' },
  { name: 'Livada', county: 'Satu Mare' },
  { name: 'Negrești-Oaș', county: 'Satu Mare' },
  { name: 'Tășnad', county: 'Satu Mare' },

  { name: 'Zalău', county: 'Sălaj' },
  { name: 'Cehu Silvaniei', county: 'Sălaj' },
  { name: 'Jibou', county: 'Sălaj' },
  { name: 'Șimleu Silvaniei', county: 'Sălaj' },

  { name: 'Sibiu', county: 'Sibiu' },
  { name: 'Agnita', county: 'Sibiu' },
  { name: 'Avrig', county: 'Sibiu' },
  { name: 'Cisnădie', county: 'Sibiu' },
  { name: 'Copșa Mică', county: 'Sibiu' },
  { name: 'Dumbrăveni', county: 'Sibiu' },
  { name: 'Mediaș', county: 'Sibiu' },
  { name: 'Miercurea Sibiului', county: 'Sibiu' },
  { name: 'Ocna Sibiului', county: 'Sibiu' },
  { name: 'Săliște', county: 'Sibiu' },
  { name: 'Tălmaciu', county: 'Sibiu' },

  { name: 'Suceava', county: 'Suceava' },
  { name: 'Broșteni', county: 'Suceava' },
  { name: 'Cajvana', county: 'Suceava' },
  { name: 'Câmpulung Moldovenesc', county: 'Suceava' },
  { name: 'Dolhasca', county: 'Suceava' },
  { name: 'Frasin', county: 'Suceava' },
  { name: 'Fălticeni', county: 'Suceava' },
  { name: 'Gura Humorului', county: 'Suceava' },
  { name: 'Liteni', county: 'Suceava' },
  { name: 'Milișăuți', county: 'Suceava' },
  { name: 'Rădăuți', county: 'Suceava' },
  { name: 'Salcea', county: 'Suceava' },
  { name: 'Siret', county: 'Suceava' },
  { name: 'Solca', county: 'Suceava' },
  { name: 'Vatra Dornei', county: 'Suceava' },
  { name: 'Vicovu de Sus', county: 'Suceava' },

  { name: 'Alexandria', county: 'Teleorman' },
  { name: 'Roșiorii de Vede', county: 'Teleorman' },
  { name: 'Turnu Măgurele', county: 'Teleorman' },
  { name: 'Videle', county: 'Teleorman' },
  { name: 'Zimnicea', county: 'Teleorman' },

  { name: 'Timișoara', county: 'Timiș' },
  { name: 'Buziaș', county: 'Timiș' },
  { name: 'Ciacova', county: 'Timiș' },
  { name: 'Deta', county: 'Timiș' },
  { name: 'Făget', county: 'Timiș' },
  { name: 'Gătaia', county: 'Timiș' },
  { name: 'Jimbolia', county: 'Timiș' },
  { name: 'Lugoj', county: 'Timiș' },
  { name: 'Recaș', county: 'Timiș' },
  { name: 'Sânnicolau Mare', county: 'Timiș' },

  { name: 'Tulcea', county: 'Tulcea' },
  { name: 'Babadag', county: 'Tulcea' },
  { name: 'Isaccea', county: 'Tulcea' },
  { name: 'Măcin', county: 'Tulcea' },
  { name: 'Sulina', county: 'Tulcea' },

  { name: 'Vaslui', county: 'Vaslui' },
  { name: 'Bârlad', county: 'Vaslui' },
  { name: 'Huși', county: 'Vaslui' },
  { name: 'Murgeni', county: 'Vaslui' },
  { name: 'Negrești', county: 'Vaslui' },

  { name: 'Râmnicu Vâlcea', county: 'Vâlcea' },
  { name: 'Băbeni', county: 'Vâlcea' },
  { name: 'Băile Govora', county: 'Vâlcea' },
  { name: 'Băile Olănești', county: 'Vâlcea' },
  { name: 'Bălcești', county: 'Vâlcea' },
  { name: 'Berbești', county: 'Vâlcea' },
  { name: 'Brezoi', county: 'Vâlcea' },
  { name: 'Călimănești', county: 'Vâlcea' },
  { name: 'Drăgășani', county: 'Vâlcea' },
  { name: 'Horezu', county: 'Vâlcea' },
  { name: 'Ocnele Mari', county: 'Vâlcea' },

  { name: 'Focșani', county: 'Vrancea' },
  { name: 'Adjud', county: 'Vrancea' },
  { name: 'Mărășești', county: 'Vrancea' },
  { name: 'Odobești', county: 'Vrancea' },
  { name: 'Panciu', county: 'Vrancea' },
];
